NEW USER/VHOST CREATED ON SERVER {$HOSTNAME}

VHOST: {$VHOST}

USER: {$USER}
UID: {$UID}
GID: {$GID}
PWD_FTP: {$PWD_FTP}
PWD_MYSQL: {$PWD_MYSQL}

DOMAIN: {$DOMAIN}

VHOST_EMAIL: {$VHOST_EMAIL}
ADMIN_EMAIL: {$ADMIN_EMAIL}

GRIVE_EMAIL: {$GRIVE_EMAIL}
GRIVE_DIR:   {$GRIVE_DIR}
GRIVE_SUBDIR_BACKUPS: {$GRIVE_SUBDIR_BACKUPS}

