CREATE USER '{$USER}'@'localhost' IDENTIFIED BY '{$PWD_MYSQL}';
GRANT USAGE ON *.* TO '{$USER}'@'localhost' IDENTIFIED BY '{$PWD_MYSQL}' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `{$USER}` CHARACTER SET = utf8;
GRANT ALL PRIVILEGES ON `{$USER}`.* TO '{$USER}'@'localhost';