NEW USER/VHOST CREATED ON SERVER {$HOSTNAME}

VHOST: {$VHOST}

USER: {$USER}
UID: {$UID}
GID: {$GID}
PWD_FTP: {$PWD_FTP}
PWD_MYSQL: {$PWD_MYSQL}

VHOST_EMAIL: {$VHOST_EMAIL}
ADMIN_EMAIL: {$ADMIN_EMAIL}
