DELETED USER FOR http://{$HOSTNAME}

USER: {$USER}
GROUP: {$GROUP}

DOMAIN: {$DOMAIN}
VHOST: http://{$VHOST}
BACKUP COPY OF VHOST IS LOCATED IN VHOSTS DIRECTORY.
OWNER OF DATA ON TGZ
  UID: {$UID}
  GID: {$GID}
